const webpack = require('webpack');
const path = require('path');

const isDist = (process.env.WEBPACK_OUTPUT === 'dist');

const outputDir = path.resolve(__dirname, (
  (isDist) ? '../../../dist/js' : 'build')
);

module.exports = {
  // Start point of the app
  entry: {
    its123api: './src/main.js',
    'its123api.polyfill': './src/polyfill.js',
    'its123api.loader': './src/loader.js',
  },

  // Add sourcemap to output
  devtool: 'source-map',


  // Output path after webpack has run
  output: {
    path: outputDir,
    filename: (isDist) ? '[name].min.js' : '[name].js',
  },
  devServer: {
      compress: true,
      disableHostCheck: true,
  },
  module: {
    // Load all js files and convert them using babel
    loaders: [
      {
        test: /\.js$/, // Transform all .js files required somewhere with Babel
        exclude: /(node_modules|bower_components)/,
        loader: 'babel-loader',
        query: {
          presets: [
            'latest',
          ],
          plugins: [
            'transform-es3-property-literals', // For IE < 10
            'transform-es3-member-expression-literals', // For IE < 10,
            'transform-object-rest-spread', // Add support for object spread
            'transform-async-functions', // Aync/await
            'transform-regenerator', // Transform generators generated by async/await
          ],
        },
      },
    ],
  },

  plugins: (isDist) ? [
    new webpack.DefinePlugin({
      'process.env': {
        'NODE_ENV': JSON.stringify('production')
      }
    }),
    // Optimize the output bundle by minifying
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false,
      },
      comments: false,
      sourceMap: true,
      mangle: true,
    }),
    new webpack.optimize.OccurrenceOrderPlugin(),
    // Remove any duplicate code
    new webpack.optimize.DedupePlugin(),

    new webpack.optimize.AggressiveMergingPlugin(),
  ] : [],
};
